import React from 'react';


const Home = () => {
  return (
    <div className="home">
      <header>
      <h1>POWER SOURCE</h1>
        <p>is showing how much</p>
        <p>of our space ship and lightsword</p>
        <p>energy we can use yet</p>
        <p>check the power level left</p>
        <p>click STATUS to see.</p>
      </header>
      <div className="section">
          <div className="article">
          <strong>The Millennium Falcon </strong>original designation YT-1300 492727ZED, was a Corellian YT-1300f light freighter most famously used by the smugglers Han Solo and Chewbacca during the Galactic Civil War. In the time following the Battle of Endor, Imperial turncoat Ralsius Paldora noted that 2.2 out of every 300 stormtroopers were aware of the Falcon's existence.[38]
          <br/><br/>
          <strong>Its aged </strong>appearance belied numerous advanced modifications to boost the ship's speed, weapons, and shield, including a hyperdrive engine among the fastest in the entire galaxy, enabling it to outrun Imperial Star Destroyers. It included sensor-proof smuggling compartments, which were used during the rescue of Princess Leia Organa in 0 BBY to evade Imperial stormtroopers.[1] Afterwards, the Millennium Falcon saw further action when Solo chose to join the Rebels during the Battle of Yavin, where it was able to sneak up and fire on Darth Vader's TIE Advanced, allowing Luke Skywalker to fire the proton torpedo that destroyed the Death Star.
          <br/><br/>
          <strong>After Han </strong> was captured on Bespin, Lando took command of the Falcon once more to search for him. In 4 ABY, Lando flew the ship at the Battle of Endor, where it entered the Death Star II and destroyed it from within. Over the next decades, the ship fell out of Solo's hands and was stolen by a succession of criminals and thieves. It ended up back in Solo's hands in 34 ABY, after it was found on Jakku, a remote world in the Western Reaches.
          </div>

          <div className="article">
          <strong>The lightsaber</strong> also referred to as a laser sword by those who were unfamiliar with it, was a distinctive weapon, the very image of which was inextricably bound with the mythos of the Jedi Order and their polar opposites, the Sith. The lightsaber also became synonymous with the Jedi Order's values to uphold peace and justice throughout the galaxy. This perception endured, despite the many conflicts with lightsaber-wielding Sith and Dark Jedi.
          <br/><br/>
          <strong>The weapon </strong>consisted of a blade of pure plasma emitted from the hilt and suspended in a force containment field. The field contained the immense heat of the plasma, protecting the wielder, and allowed the blade to keep its shape. The hilt was almost always self-fabricated by the wielder to match his or her specific needs, preferences and style. The hilt was also built similarly to his or her master's lightsaber as a mark of respect. Due to the weightlessness of plasma and the strong gyroscopic effect generated by it, lightsabers required a great deal of strength and dexterity to wield, and it was extremely difficult—and dangerous—for the untrained to attempt using. 
          <br/><br/>
          <strong>However</strong>, in the hands of an expert of the Force, the lightsaber was a weapon to be greatly respected and feared. To wield a lightsaber was to demonstrate incredible skill and confidence, as well as masterful dexterity and attunement to the Force.
          </div>

          <div className="article">
            <strong>Power control</strong> is very impornat to not ramain without energy, so check frequiently how much Your space ship and lightsword has energy left to be ready plug into <strong>power source </strong>on time.
            </div>

        </div>
        <footer>Copyright all reserved 2019</footer>
    </div>
  );
}

export default Home;